# Generated by Django 6.0.7 on 2026-10-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('conteudo', models.TextField(verbose_name='Conteudo do Post')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Postado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Editado em')),
            ],
            options={
                'verbose_name': 'Post',
                'ordering': ['created_at'],
            },
        ),
    ]
