# Generated by Django 6.0.7 on 2026-09-30 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='name_client',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
